export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const APISTATUS = "APISTATUS";
export const LOGINREQUEST = "LOGIN-REQUEST";
export const STUDENTPROGRAMSLUT = "STUDENTPROGRAMSLUT";
